### ISSUE TITLE
課題 (0113) Rx復習 + ScriptableObject

### ISSUE THREAD

**Issue by SentioMe** [ilgonSon/SampleRepository#6]
## 課題

- ScriptableObjectでデータ化
- データは、常に非同期でロードする
- 敵の数・bulletの速度や連射などをすべて、データ化する
- 敵のデータ・プレイヤーの設定データなどをそれぞれ分けて、データを定義する
- 左・右の移動とBulletの発射は、ボタンとキー入力を両方許容する
  - 同じ処理のキーが同時入力の場合 (左ボタンと⇦キーを同時入力など)は、一定間隔で反映されるようにする ( ex. ThrottleXXX )
- 概念単位で型を分けて、互いを知らない実装にする
  - 操作UIと味方の飛行機は互いを直接的に知らない
- 全ての敵を倒すと次のwaveに変わる (敵は、wave単位で別色でしてください)
- Bulletと敵はpoolingする
- 色設定は、遅延処理で行う (= イメージの非同期ロードの代わりに色設定にしています)

![Galaga](https://user-images.githubusercontent.com/15889372/104462775-53213b00-55f4-11eb-9ec7-cc851728d6fc.png)

##

**Comment by ilgonSon** [comment]
## 조작

- [ ] 캐릭  -> 조작에 의한 행동반응
- [ ] 조작 -> 버튼입력동작(키홀드반응) 키입력 동작
- [ ] 캐릭data -> 색, 최대 이동범위, 속도

## 사격

- [ ] 캐릭 -> 조작에 의한 발사반응
- [ ] 조작 -> 버튼,키 입력동장
- [ ] 총알 -> 이동운동, 일정량 이동후 Poolling
- [ ] pool관리 -> 생성최대량, 돌리기
- [ ] 총알 data -> 속도, 간격

## 적

- [ ] 총알 -> 충돌처리(poolling)
- [ ] 적 -> 충돌반응(poolling)
- [ ] AI -> 적 이동, 행동반경
- [ ] pool관리 -> 존재량, 재배치
- [ ] 적 data -> 색, 속도, hp?

**Comment by SentioMe** [comment]
![関係](https://user-images.githubusercontent.com/15889372/104812183-e4d2b780-5843-11eb-8056-d135c57b4273.png)
