### ISSUE TITLE
課題 (0113) Rx・Unity練習 (頑張れ車)

### ISSUE THREAD

**Issue by SentioMe** [ilgonSon/SampleRepository#8]
![image](https://user-images.githubusercontent.com/15889372/105572479-b94b5200-5d9a-11eb-8916-ba2d3340abe9.png)

플레이어 움직임
- 자동으로 앞으로 간다
- 키입력으로 좌우꺽는다

UI
- 한바퀴 돌때마다
  - 1/ 3 랩상승하는거 표시 (대충 오른쪽 위 UI)
  - 완주시간
  - 두번째 바퀴부터 이전랩과 비교해서 차이 표시
    - 이전이란 상태값은 없음
  - 왼쪽 위에 현재 시간

씬
1. 로드 하는 씬
2. 게임 씬
  - 결과 UI
3. 아웃 씬
  - 자동차 바꿀 수 있게
  - ◀ 현재 페이지 / 총 차량수　▶
    - 클릭
    - 선택 버튼
    - 누르면 자동차 선택되서 2번 씬으로 이동
    - UI열릴때 현재 페이지는 자기가 선택중이었던 자동차의 페이지부터시작

자동차 별 스테이터스
  - 속도
  - 사이즈 (앞뒤 길이)
  - 색깔
  - 코너링 속도

1 -> 2 -> 3-> 2(루프)

**Comment by ilgonSon** [comment]
## 조작
- [ ] 핸들링
- [ ] 등속이동
## 씬
- [ ] 로드씬
- [ ] 게임씬
- [ ] 아웃씬
## UI
- [ ] 현재Rap / 총Rap
- [ ] 경과시간
- [ ] 이전 rap타임과 비교시간
- [ ] 결과 UI
- [ ] 차량변경
## Data
- [ ] 차량 모델 (속도, 사이즈, 색)
